export const coloresEmpresa=['#2b1c6b' ,"#99c343"];
export const nombreUnidadesTrabajo="cajas";
export const simboloMoneda="€";
export const tipoUsuarioVendedor="vendedor"
export const tipoUsuarioCliente="cliente"
export const pedidoBaseOpcion="cargarPedidoBase"
export const pedidoBase_pedidoSeleccionado='Cargar el pedido base';
export const pedidoBase_ultimoPedido='Cargar el último pedido';
export const franjaHorariaGeneralBooleanOpcion="franjaHorariaGeneralBooleanOpcion"
export const productosSinStockBoolean="productosSinStock"
export const opcionesGlobalesVendedorString="opcionesGlobales";
export const franjasHorariasString="franjasHorarias"
export const franjaHorariaGeneralOpcion="franjaHorariaGeneralOpcion"
export const BAD_REQUEST=400;
export const INTERNAL_SERVER_ERROR=500;
export const mensajePedidoCargado=" Pedido cargado"
export const mensajePasswordGuardadoCorrectamente="Contraseña modificada correctamente"
export const mensajePasswordNoGuardado="No sea ha podido cambiar la contraseña"
export const mensajeErrorFranjasHorarias="No puedes realizar el pedido ahora. Comprueba las franjas horarias en Perfil"
export const mensajeErrorMaximoCajas="No se pueden hacer pedidos de más de 1000 cajas"
export const mensajeErrorServidor="Error de servidor"
export const mensajeErrorPeticionPedido=" El pedido esta vacío por lo que se no se ha guardado"
export const mensajeErrorClienteBadRequest=" No se ha podido guardar el cliente."
export const mensajeErrorGuardarPedido="No se puede guardar.El pedido está vacío"
export const maxCaracters=25;
export const mensajeErrorDemasiadosCaracteres ="Nombre demasiado largo. Máximo "+maxCaracters+" caracteres"
export const mensajeErrorCampoErroneo="Campo erróneo."
export const mensajeErrorPasswordsNoCoincide="Las contraseñas deben coincidir"
export const mensajeGuardadoCliente=" Cliente guardado correctamente"
export const mensajeEliminadoCliente=" Cliente eliminado"
export const mensajeGuardadoFranjaHoraria= " Franja horaria guardado correctamente"
export const mensajeEliminadoFranjaHoraria=" Franja horaria eliminada"
export const mensajeErrorEliminadoCliente=" No se ha podido eliminar el cliente"
export const mensajeErrorEliminadoFranjaHoraria=" No se ha podido eliminar la franja horaria"
export const weekdays = ["todos","lunes","martes","miércoles","jueves","viernes","sábado","domingo"]
export const dictWeekdays={"Lunes":0,"Martes":1,"Miercoles":2,"Jueves":3,"Viernes":4,"Sabado":5,"Domingo":6}
export const badLogin="Credenciales incorrectas"
export const errorDeRed="Error de conexión con el servidor. Comprueba tu conexión a Internet"
export const mensajePedidoBorrado="Pedido borrado. Tu pedido está vacío."
export const imagePath = {
    'gama impulso_NUII_Nuii Almendrado con vainilla de Java': require('../../assets/product_images/gama_impulso/NUII/Nuii_Almendrado_con_vainilla_de_Java.png'),
    'gama impulso_NUII_Nuii Caramelo con Nueces macadamia': require('../../assets/product_images/gama_impulso/NUII/Nuii_Caramelo_con_Nueces_macadamia.png'),
    'gama impulso_NUII_Nuii Almendrado blanco con vainilla': require('../../assets/product_images/gama_impulso/NUII/Nuii_Almendrado_blanco_con_vainilla.png'),
    'gama impulso_NUII_Nuii Chocolate negro con arándanos': require('../../assets/product_images/gama_impulso/NUII/Nuii_Chocolate_negro_con_arandanos.png'),
    'gama impulso_NUII_Nuii Mascarpone con arándanos rojos': require('../../assets/product_images/gama_impulso/NUII/Nuii_Mascarpone_con_arandanos_rojos.png'),
    'gama impulso_NUII_Nuii Nata-Chocolate negro con almendras': require('../../assets/product_images/gama_impulso/NUII/Nuii_Nata-Chocolate_negro_con_almendras.png'),
    'gama impulso_Extreme_Extreme Cono Cookie Chocolate': require('../../assets/product_images/gama_impulso/Extreme/Extreme_Cono_Cookie_Chocolate.png'),
    'gama impulso_Extreme_Extreme Cono Cookie Vainilla Caramelo': require('../../assets/product_images/gama_impulso/Extreme/Extreme_Cono_Cookie_Vainilla_Caramelo.png'),
    'gama impulso_Extreme_Extreme Nata': require('../../assets/product_images/gama_impulso/Extreme/Extreme_Nata.png'),
    'gama impulso_Extreme_Extreme Doble Chocolate': require('../../assets/product_images/gama_impulso/Extreme/Extreme_Doble_Chocolate.png'),
    'gama impulso_Extreme_Extreme Nata - Fresa': require('../../assets/product_images/gama_impulso/Extreme/Extreme_Nata_-_Fresa.png'),
    'gama impulso_Extreme_Extreme Doble Vainilla': require('../../assets/product_images/gama_impulso/Extreme/Extreme_Doble_Vainilla.png'),
    'gama impulso_Maxibon_Maxibon Jungly': require('../../assets/product_images/gama_impulso/Maxibon/Maxibon_Jungly.png'),
    'gama impulso_Maxibon_Maxibon Waffle': require('../../assets/product_images/gama_impulso/Maxibon/Maxibon_Waffle.png'),
    'gama impulso_Maxibon_Maxibon Nata': require('../../assets/product_images/gama_impulso/Maxibon/Maxibon_Nata.png'),
    'gama impulso_Maxibon_Maxibon Cookie': require('../../assets/product_images/gama_impulso/Maxibon/Maxibon_Cookie.png'),
    'gama impulso_Maxibon_Maxibon Pops': require('../../assets/product_images/gama_impulso/Maxibon/Maxibon_Pops.png'),
    'gama impulso_Pirulo_Pirulo Ocean Adventure': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Ocean_Adventure.png'),
    'gama impulso_Pirulo_Pirulo Frutti': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Frutti.png'),
    'gama impulso_Pirulo_Pirulo Fantasmikos': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Fantasmikos.png'),
    'gama impulso_Pirulo_Pirulo Sandía': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Sandia.png'),
    'gama impulso_Pirulo_Pirulo Tropical': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Tropical.png'),
    'gama impulso_Pirulo_Pirulo Cool Limón': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Cool_Limon.png'),
    'gama impulso_Pirulo_Pirulo Cool Fresa': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Cool_Fresa.png'),
    'gama impulso_Pirulo_Pirulo Mikolápiz Vainilla': require('../../assets/product_images/gama_impulso/Pirulo/Pirulo_Mikolapiz_Vainilla.png'),
    'gama impulso_Oreo_Oreo Stick Sándwich': require('../../assets/product_images/gama_impulso/Oreo/Oreo_Stick_Sandwich.png'),
    'gama impulso_Oreo_Oreo Sándwich': require('../../assets/product_images/gama_impulso/Oreo/Oreo_Sandwich.png'),
    'gama impulso_Oreo_Oreo Bombón': require('../../assets/product_images/gama_impulso/Oreo/Oreo_Bombon.png'),
    'gama impulso_Milka_Milka Bombón Chocolate': require('../../assets/product_images/gama_impulso/Milka/Milka_Bombon_Chocolate.png'),
    'gama impulso_Milka_Cono Milka': require('../../assets/product_images/gama_impulso/Milka/Cono_Milka.png'),
    'gama impulso_Toblerone_Toblerone Bombón': require('../../assets/product_images/gama_impulso/Toblerone/Toblerone_Bombon.png'),
    'gama impulso_KitKat_Cono KitKat': require('../../assets/product_images/gama_impulso/KitKat/Cono_KitKat.png'),
    'gama impulso_Clásicos de siempre_Smarties Push Up': require('../../assets/product_images/gama_impulso/Clásicos_de_siempre/Smarties_Push_Up.png'),
    'gama impulso_Clásicos de siempre_Chococlack': require('../../assets/product_images/gama_impulso/Clásicos_de_siempre/Chococlack.png'),
    'gama impulso_Clásicos de siempre_Colajet': require('../../assets/product_images/gama_impulso/Clásicos_de_siempre/Colajet.png'),
    'gama impulso_Clásicos de siempre_Sándwich nata': require('../../assets/product_images/gama_impulso/Clásicos_de_siempre/Sandwich_nata.png'),
    'nescafe frappelatte_Productos Frappélatte_Frappelatte 4,7 L': require('../../assets/product_images/nescafe_frappelatte/Productos_Frappélatte/Frappelatte_4_7_L.png'),
    'nescafe frappelatte_Productos Frappélatte_Frappelatte 2 x 2.9 L': require('../../assets/product_images/nescafe_frappelatte/Productos_Frappélatte/Frappelatte_2_x_2_9_L.png'),
    'nescafe frappelatte_Consumibles_Pajita cartón kraft 7 x 150mm': require('../../assets/product_images/nescafe_frappelatte/Consumibles/Pajita_carton_kraft_7_x_150mm.png'),
    'nescafe frappelatte_Consumibles_Vaso cartón para llevar grande': require('../../assets/product_images/nescafe_frappelatte/Consumibles/Vaso_carton_para_llevar_grande.png'),
    'nescafe frappelatte_Consumibles_Vaso cartón para llevar pequeño': require('../../assets/product_images/nescafe_frappelatte/Consumibles/Vaso_carton_para_llevar_pequeno.png'),
    'nescafe frappelatte_Consumibles_Vaso Cristal Grande': require('../../assets/product_images/nescafe_frappelatte/Consumibles/Vaso_Cristal_Grande.png'),
    'nescafe frappelatte_Consumibles_Vaso Cristal Pequeño': require('../../assets/product_images/nescafe_frappelatte/Consumibles/Vaso_Cristal_Pequeno.png'),
    'nescafe frappelatte_Toppings_Aerosol Nata Montada': require('../../assets/product_images/nescafe_frappelatte/Toppings/Aerosol_Nata_Montada.png'),
    'nescafe frappelatte_Toppings_Sirope de Caramelo': require('../../assets/product_images/nescafe_frappelatte/Toppings/Sirope_de_Caramelo.png'),
    'nescafe frappelatte_Toppings_Sirope de Fresa': require('../../assets/product_images/nescafe_frappelatte/Toppings/Sirope_de_Fresa.png'),
    'nescafe frappelatte_Toppings_Sirope de Chocolate': require('../../assets/product_images/nescafe_frappelatte/Toppings/Sirope_de_Chocolate.png'),
    'postres helados a la carta_Mini tartas heladas_Porción Caramelo': require('../../assets/product_images/postres_helados_a_la_carta/Mini_tartas_heladas/Porcion_Caramelo.png'),
    'postres helados a la carta_Mini tartas heladas_Vainilla & Cookies': require('../../assets/product_images/postres_helados_a_la_carta/Mini_tartas_heladas/Vainilla___Cookies.png'),
    'postres helados a la carta_Mini tartas heladas_Mini carolina nata': require('../../assets/product_images/postres_helados_a_la_carta/Mini_tartas_heladas/Mini_carolina_nata.png'),
    'postres helados a la carta_Mini tartas heladas_Biscuit al caramelo y piñones': require('../../assets/product_images/postres_helados_a_la_carta/Mini_tartas_heladas/Biscuit_al_caramelo_y_pinones.png'),
    'postres helados a la carta_Mini tartas heladas_Porción crocanti': require('../../assets/product_images/postres_helados_a_la_carta/Mini_tartas_heladas/Porcion_crocanti.png'),
    'postres helados a la carta_Tartas heladas_Gran dama whisky': require('../../assets/product_images/postres_helados_a_la_carta/Tartas_heladas/Gran_dama_whisky.png'),
    'postres helados a la carta_Tartas heladas_Princesa Tarta de la abuela': require('../../assets/product_images/postres_helados_a_la_carta/Tartas_heladas/Princesa_Tarta_de_la_abuela.png'),
    'postres helados a la carta_Tartas heladas_Tarta CAROLINA nata': require('../../assets/product_images/postres_helados_a_la_carta/Tartas_heladas/Tarta_CAROLINA_nata.png'),
    'postres helados a la carta_Tartas heladas_Tarta Clásica': require('../../assets/product_images/postres_helados_a_la_carta/Tartas_heladas/Tarta_Clasica.png'),
    'postres helados a la carta_Tartas heladas_Tarta gourmet whisky': require('../../assets/product_images/postres_helados_a_la_carta/Tartas_heladas/Tarta_gourmet_whisky.png'),
    'postres helados a la carta_Recetas artesanas_Crema catalana': require('../../assets/product_images/postres_helados_a_la_carta/Recetas_artesanas/Crema_catalana.png'),
    'postres helados a la carta_Recetas artesanas_Tarrina al whisky': require('../../assets/product_images/postres_helados_a_la_carta/Recetas_artesanas/Tarrina_al_whisky.png'),
    'postres helados a la carta_Frutas heladas_Limón helado': require('../../assets/product_images/postres_helados_a_la_carta/Frutas_heladas/Limon_helado.png'),
    'postres helados a la carta_Frutas heladas_Coco helado': require('../../assets/product_images/postres_helados_a_la_carta/Frutas_heladas/Coco_helado.png'),
    'postres helados a la carta_Infantiles helados_Monster': require('../../assets/product_images/postres_helados_a_la_carta/Infantiles_helados/Monster.png'),
    'postres helados a la carta_Infantiles helados_Caja Lady Bug': require('../../assets/product_images/postres_helados_a_la_carta/Infantiles_helados/Caja_Lady_Bug.png'),
    'postres helados a la carta_Infantiles helados_León Sin Gluten': require('../../assets/product_images/postres_helados_a_la_carta/Infantiles_helados/Leon_Sin_Gluten.png'),
    'postres helados a la carta_Infantiles helados_Smarties Fun Cup': require('../../assets/product_images/postres_helados_a_la_carta/Infantiles_helados/Smarties_Fun_Cup.png'),
    'postres helados a la carta_Snacking_Bombones helados': require('../../assets/product_images/postres_helados_a_la_carta/Snacking/Bombones_helados.png'),
    'postres helados a la carta_Snacking_Trufas heladas': require('../../assets/product_images/postres_helados_a_la_carta/Snacking/Trufas_heladas.png'),
    'postres helados a la carta_Snacking_Bocaditos oreo': require('../../assets/product_images/postres_helados_a_la_carta/Snacking/Bocaditos_oreo.png'),
    'postres helados a la carta_Copas y tubs_Lechera Suprema Vainilla Pecan': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Lechera_Suprema_Vainilla_Pecan.png'),
    'postres helados a la carta_Copas y tubs_Lechera Suprema Turrón': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Lechera_Suprema_Turron.png'),
    'postres helados a la carta_Copas y tubs_Lechera Suprema Chocolate Absoluto': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Lechera_Suprema_Chocolate_Absoluto.png'),
    'postres helados a la carta_Copas y tubs_Lechera Cheesecake Frambuesa': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Lechera_Cheesecake_Frambuesa.png'),
    'postres helados a la carta_Copas y tubs_Sensación de limón': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Sensacion_de_limon.png'),
    'postres helados a la carta_Copas y tubs_Sensación Turrón': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Sensacion_Turron.png'),
    'postres helados a la carta_Copas y tubs_Sensación de frutos rojos': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Sensacion_de_frutos_rojos.png'),
    'postres helados a la carta_Copas y tubs_Sensación chocolate': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Sensacion_chocolate.png'),
    'postres helados a la carta_Copas y tubs_Le tentazione tiramisú': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Le_tentazione_tiramisu.png'),
    'postres helados a la carta_Copas y tubs_Le tentazione panna e cioccolato': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Le_tentazione_panna_e_cioccolato.png'),
    'postres helados a la carta_Copas y tubs_Le Tentazione Caffe': require('../../assets/product_images/postres_helados_a_la_carta/Copas_y_tubs/Le_Tentazione_Caffe.png'),
    'la lechera_Graneles especial heladerías_Vainilla 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Vainilla_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Chocolate 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Chocolate_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Nata 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Nata_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Fresa 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Fresa_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Limón 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Limon_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Leche Merengada 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Leche_Merengada_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Café 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Cafe_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Dulce De Leche 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Dulce_De_Leche_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Coco 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Coco_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Pasas al ron 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Pasas_al_ron_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Turrón 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Turron_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Cheesecake 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Cheesecake_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Yogur Con Salsa Frambuesa 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Yogur_Con_Salsa_Frambuesa_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Tarta de la Abuela 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Tarta_de_la_Abuela_5_5L_.png'),
    'la lechera_Graneles especial heladerías_KitKat 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/KitKat_5_5L_.png'),
    'la lechera_Graneles especial heladerías_After Eight 5,5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/After_Eight_5_5L_.png'),
    'la lechera_Graneles especial heladerías_Stracciatella 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Stracciatella_5L_.png'),
    'la lechera_Graneles especial heladerías_Oreo 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Oreo_5L_.png'),
    'la lechera_Graneles especial heladerías_Milka Chocolate 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Milka_Chocolate_5L_.png'),
    'la lechera_Graneles especial heladerías_Lion Caramelo y Galleta 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Lion_Caramelo_y_Galleta_5L_.png'),
    'la lechera_Graneles especial heladerías_Vainilla Brownie Caramelo 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Vainilla_Brownie_Caramelo_5L_.png'),
    'la lechera_Graneles especial heladerías_Turrón Blanco 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Turron_Blanco_2_4L_.png'),
    'la lechera_Graneles especial heladerías_Avellana 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Avellana_2_4L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de Melocotón 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_Melocoton_2_4L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de Lima 2.4L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_Lima_2_4L_.png'),
    'la lechera_Graneles especial heladerías_Plátano 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Platano_2_4L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de fruta de la pasión 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_fruta_de_la_pasion_2_4L_.png'),
    'la lechera_Graneles especial heladerías_Vainilla 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Vainilla_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Fresa 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Fresa_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Chocolate 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Chocolate_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Turrón 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Turron_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Galleta María 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Galleta_Maria_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Nata nueces 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Nata_nueces_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Pistacho 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Pistacho_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de Mojito 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_Mojito_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de Piña 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_Pina_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Vainilla 0% Azúcares Añadidos 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Vainilla_0__Azucares_Anadidos_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de limón 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_limon_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de manzana 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_manzana_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de Mango 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_Mango_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete de frambuesa 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_de_frambuesa_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Sorbete Mandarina 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Sorbete_Mandarina_2_1L_.png'),
    'la lechera_Graneles especial heladerías_Chocolate Blanco 2,035L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Chocolate_Blanco_2_035L_.png'),
    'la lechera_Graneles especial heladerías_Amarena 2,035L.': require('../../assets/product_images/la_lechera/Graneles_especial_heladerías/Amarena_2_035L_.png'),
    'la lechera_Graneles especial restauración_Vainilla 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Vainilla_5_5L_.png'),
    'la lechera_Graneles especial restauración_Chocolate 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Chocolate_5_5L_.png'),
    'la lechera_Graneles especial restauración_Nata 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Nata_5_5L_.png'),
    'la lechera_Graneles especial restauración_Fresa 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Fresa_5_5L_.png'),
    'la lechera_Graneles especial restauración_Limón 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Limon_5_5L_.png'),
    'la lechera_Graneles especial restauración_Leche merengada 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Leche_merengada_5_5L_.png'),
    'la lechera_Graneles especial restauración_Café 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Cafe_5_5L_.png'),
    'la lechera_Graneles especial restauración_Dulce de leche 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Dulce_de_leche_5_5L_.png'),
    'la lechera_Graneles especial restauración_Coco 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Coco_5_5L_.png'),
    'la lechera_Graneles especial restauración_Pasas al ron 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Pasas_al_ron_5_5L_.png'),
    'la lechera_Graneles especial restauración_Turrón 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Turron_5_5L_.png'),
    'la lechera_Graneles especial restauración_Cheesecake 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Cheesecake_5_5L_.png'),
    'la lechera_Graneles especial restauración_Yogur Frambuesa 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Yogur_Frambuesa_5_5L_.png'),
    'la lechera_Graneles especial restauración_Tarta de la abuela 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Tarta_de_la_abuela_5_5L_.png'),
    'la lechera_Graneles especial restauración_KitKat 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/KitKat_5_5L_.png'),
    'la lechera_Graneles especial restauración_After Eight 5.5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/After_Eight_5_5L_.png'),
    'la lechera_Graneles especial restauración_Stracciatella 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Stracciatella_5L_.png'),
    'la lechera_Graneles especial restauración_Oreo 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Oreo_5L_.png'),
    'la lechera_Graneles especial restauración_Milka Chocolate 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Milka_Chocolate_5L_.png'),
    'la lechera_Graneles especial restauración_Lion Caramelo y Galleta 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Lion_Caramelo_y_Galleta_5L_.png'),
    'la lechera_Graneles especial restauración_Vainilla Brownie Caramelo 5L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Vainilla_Brownie_Caramelo_5L_.png'),
    'la lechera_Graneles especial restauración_Turrón Blanco 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Turron_Blanco_2_4L_.png'),
    'la lechera_Graneles especial restauración_Avellana 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Avellana_2_4L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de Melocotón 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_Melocoton_2_4L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de Lima 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_Lima_2_4L_.png'),
    'la lechera_Graneles especial restauración_Sorbete fruta de la pasión 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_fruta_de_la_pasion_2_4L_.png'),
    'la lechera_Graneles especial restauración_Plátano 2,4L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Platano_2_4L_.png'),
    'la lechera_Graneles especial restauración_Vainilla 2,1L': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Vainilla_2_1L.png'),
    'la lechera_Graneles especial restauración_Fresa 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Fresa_2_1L_.png'),
    'la lechera_Graneles especial restauración_Chocolate 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Chocolate_2_1L_.png'),
    'la lechera_Graneles especial restauración_Turrón 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Turron_2_1L_.png'),
    'la lechera_Graneles especial restauración_Galleta María 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Galleta_Maria_2_1L_.png'),
    'la lechera_Graneles especial restauración_Nata nueces 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Nata_nueces_2_1L_.png'),
    'la lechera_Graneles especial restauración_Pistacho 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Pistacho_2_1L_.png'),
    'la lechera_Graneles especial restauración_Vainilla sin azúcar 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Vainilla_sin_azucar_2_1L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de mojito 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_mojito_2_1L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de piña 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_pina_2_1L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de limón 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_limon_2_1L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de Manzana Verde 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_Manzana_Verde_2_1L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de Mango 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_Mango_2_1L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de frambuesa 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_frambuesa_2_1L_.png'),
    'la lechera_Graneles especial restauración_Sorbete de mandarina. 2,1L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Sorbete_de_mandarina__2_1L_.png'),
    'la lechera_Graneles especial restauración_Chocolate Blanco 2,035L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Chocolate_Blanco_2_035L_.png'),
    'la lechera_Graneles especial restauración_Amarena 2,035L.': require('../../assets/product_images/la_lechera/Graneles_especial_restauración/Amarena_2_035L_.png'),
    'la lechera_Toppings_Aerosol Nata Montada': require('../../assets/product_images/la_lechera/Toppings/Aerosol_Nata_Montada.png'),
    'la lechera_Toppings_Sirope de Caramelo': require('../../assets/product_images/la_lechera/Toppings/Sirope_de_Caramelo.png'),
    'la lechera_Toppings_Sirope de Fresa': require('../../assets/product_images/la_lechera/Toppings/Sirope_de_Fresa.png'),
    'la lechera_Toppings_Sirope de Chocolate': require('../../assets/product_images/la_lechera/Toppings/Sirope_de_Chocolate.png'),
    'la lechera_Consumibles_Cucharita madera envuelta individual': require('../../assets/product_images/la_lechera/Consumibles/Cucharita_madera_envuelta_individual.png'),
    'la lechera_Consumibles_Vaso Plástico 100% Compostable 400ml': require('../../assets/product_images/la_lechera/Consumibles/Vaso_Plastico_100__Compostable_400ml.png'),
    'la lechera_Consumibles_Barquillo Artesano 45': require('../../assets/product_images/la_lechera/Consumibles/Barquillo_Artesano_45.png'),
    'la lechera_Consumibles_Tapa cúpula plástico 100% compostable': require('../../assets/product_images/la_lechera/Consumibles/Tapa_cupula_plastico_100__compostable.png'),
    'la lechera_Consumibles_Pajita cartón kraft 8 x 200mm': require('../../assets/product_images/la_lechera/Consumibles/Pajita_carton_kraft_8_x_200mm.png'),
    'la lechera_Consumibles_Barquillo Artesano 50': require('../../assets/product_images/la_lechera/Consumibles/Barquillo_Artesano_50.png'),
    'la lechera_Consumibles_Barquillo Artesano 55': require('../../assets/product_images/la_lechera/Consumibles/Barquillo_Artesano_55.png'),
    'la lechera_Consumibles_Galleta corte': require('../../assets/product_images/la_lechera/Consumibles/Galleta_corte.png'),
    'la lechera_Consumibles_Cono Papel La Lechera Artesana': require('../../assets/product_images/la_lechera/Consumibles/Cono_Papel_La_Lechera_Artesana.png'),
    'la lechera_Consumibles_Vasito La Lechera Artesana Pequeño': require('../../assets/product_images/la_lechera/Consumibles/Vasito_La_Lechera_Artesana_Pequeno.png'),
    'la lechera_Consumibles_Vasito La Lechera Artesana Mediano': require('../../assets/product_images/la_lechera/Consumibles/Vasito_La_Lechera_Artesana_Mediano.png'),
    'la lechera_Consumibles_Vasito La Lechera Artesana Grande': require('../../assets/product_images/la_lechera/Consumibles/Vasito_La_Lechera_Artesana_Grande.png'),
    'la lechera_Consumibles_Envase Granel Porex 1 l': require('../../assets/product_images/la_lechera/Consumibles/Envase_Granel_Porex_1_l.png'),
    'la lechera_Consumibles_Envase Granel Porex 0,5 l': require('../../assets/product_images/la_lechera/Consumibles/Envase_Granel_Porex_0_5_l.png'),
    'graneles AGDC_Cremas_Cioccolato': require('../../assets/product_images/graneles_AGDC/Cremas/Cioccolato.png'),
    'graneles AGDC_Cremas_Vaniglia del Madagascar': require('../../assets/product_images/graneles_AGDC/Cremas/Vaniglia_del_Madagascar.png'),
    'graneles AGDC_Cremas_Nocciola': require('../../assets/product_images/graneles_AGDC/Cremas/Nocciola.png'),
    'graneles AGDC_Cremas_Stracciatella': require('../../assets/product_images/graneles_AGDC/Cremas/Stracciatella.png'),
    'graneles AGDC_Cremas_Fiordilatte': require('../../assets/product_images/graneles_AGDC/Cremas/Fiordilatte.png'),
    'graneles AGDC_Cremas_Tiramisù al Mascarpone': require('../../assets/product_images/graneles_AGDC/Cremas/Tiramisù_al_Mascarpone.png'),
    'graneles AGDC_Cremas_Caffè Arabica e Robusta': require('../../assets/product_images/graneles_AGDC/Cremas/Caffè_Arabica_e_Robusta.png'),
    'graneles AGDC_Cremas_Cocco': require('../../assets/product_images/graneles_AGDC/Cremas/Cocco.png'),
    'graneles AGDC_Cremas_Pistacchio de Sicilia': require('../../assets/product_images/graneles_AGDC/Cremas/Pistacchio_de_Sicilia.png'),
    'graneles AGDC_Cremas_Yogurt Frutti di Bosco': require('../../assets/product_images/graneles_AGDC/Cremas/Yogurt_Frutti_di_Bosco.png'),
    'graneles AGDC_Sorbetes_Sorbete Ananas': require('../../assets/product_images/graneles_AGDC/Sorbetes/Sorbete_Ananas.png'),
    'graneles AGDC_Sorbetes_Sorbete Mango': require('../../assets/product_images/graneles_AGDC/Sorbetes/Sorbete_Mango.png'),
    'graneles AGDC_Sorbetes_Sorbete Limone di Sicilia': require('../../assets/product_images/graneles_AGDC/Sorbetes/Sorbete_Limone_di_Sicilia.png'),
    'graneles AGDC_Sorbetes_Sorbete Fragola': require('../../assets/product_images/graneles_AGDC/Sorbetes/Sorbete_Fragola.png'),
    'graneles AGDC_Consumibles_Vaso Plástico 100% Compostable 400ml': require('../../assets/product_images/graneles_AGDC/Consumibles/Vaso_Plastico_100__Compostable_400ml.png'),
    'graneles AGDC_Consumibles_Pajita cartón kraft 8 x 200mm': require('../../assets/product_images/graneles_AGDC/Consumibles/Pajita_carton_kraft_8_x_200mm.png'),
    'graneles AGDC_Consumibles_Cucharita madera envuelta individual': require('../../assets/product_images/graneles_AGDC/Consumibles/Cucharita_madera_envuelta_individual.png'),
    'graneles AGDC_Consumibles_Tapa cúpula plástico 100% compostable': require('../../assets/product_images/graneles_AGDC/Consumibles/Tapa_cupula_plastico_100__compostable.png'),
    'graneles AGDC_Consumibles_Envase Granel Porex 1 L.': require('../../assets/product_images/graneles_AGDC/Consumibles/Envase_Granel_Porex_1_L_.png'),
    'graneles AGDC_Consumibles_Envase Granel Porex 0,5L': require('../../assets/product_images/graneles_AGDC/Consumibles/Envase_Granel_Porex_0_5L.png'),
    'graneles AGDC_Consumibles_Cono Papel AGDC': require('../../assets/product_images/graneles_AGDC/Consumibles/Cono_Papel_AGDC.png'),
    'graneles AGDC_Consumibles_Tarrina Pequeña AGDC 100 ml': require('../../assets/product_images/graneles_AGDC/Consumibles/Tarrina_Pequena_AGDC_100_ml.png'),
    'graneles AGDC_Consumibles_Tarrina Mediana AGDC 175 ml': require('../../assets/product_images/graneles_AGDC/Consumibles/Tarrina_Mediana_AGDC_175_ml.png'),
    'graneles AGDC_Consumibles_Tarrina Grande AGDC 260 ml': require('../../assets/product_images/graneles_AGDC/Consumibles/Tarrina_Grande_AGDC_260_ml.png'),
    'pasteleria_Tartas redondas enteras_Lemon Pie 1KG': require('../../assets/product_images/pasteleria/Tartas_redondas_enteras/Lemon_Pie_1KG.png'),
    'pasteleria_Tartas redondas enteras_Tarta de Queso Artesana': require('../../assets/product_images/pasteleria/Tartas_redondas_enteras/Tarta_de_Queso_Artesana.png'),
    'pasteleria_Tartas redondas enteras_Tarta de Almendras': require('../../assets/product_images/pasteleria/Tartas_redondas_enteras/Tarta_de_Almendras.png'),
    'pasteleria_Tartas redondas enteras_Tarta mousse de queso con frambuesa': require('../../assets/product_images/pasteleria/Tartas_redondas_enteras/Tarta_mousse_de_queso_con_frambuesa.png'),
    'pasteleria_Tartas redondas enteras_Tarta Mousse de Chocolate': require('../../assets/product_images/pasteleria/Tartas_redondas_enteras/Tarta_Mousse_de_Chocolate.png'),
    'pasteleria_Tartas redondas precortadas_Tarta ricotta e pera': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Tarta_ricotta_e_pera.png'),
    'pasteleria_Tartas redondas precortadas_Tarta de Queso con Arándanos Premium': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Tarta_de_Queso_con_Arandanos_Premium.png'),
    'pasteleria_Tartas redondas precortadas_Tarta Cookies Cheesecake Cacao': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Tarta_Cookies_Cheesecake_Cacao.png'),
    'pasteleria_Tartas redondas precortadas_Red Velvet': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Red_Velvet.png'),
    'pasteleria_Tartas redondas precortadas_Carrot Cake': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Carrot_Cake.png'),
    'pasteleria_Tartas redondas precortadas_Tarta de queso y arándanos': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Tarta_de_queso_y_arandanos.png'),
    'pasteleria_Tartas redondas precortadas_Tarta de Fresas': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Tarta_de_Fresas.png'),
    'pasteleria_Tartas redondas precortadas_Tarta manzana': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Tarta_manzana.png'),
    'pasteleria_Tartas redondas precortadas_Tarta de Queso y Dulce de Leche': require('../../assets/product_images/pasteleria/Tartas_redondas_precortadas/Tarta_de_Queso_y_Dulce_de_Leche.png'),
    'pasteleria_Tarta rectangulares_Tarta Tiramisú Savoiardi': require('../../assets/product_images/pasteleria/Tarta_rectangulares/Tarta_Tiramisu_Savoiardi.png'),
    'pasteleria_Tarta rectangulares_Tarta Milhojas': require('../../assets/product_images/pasteleria/Tarta_rectangulares/Tarta_Milhojas.png'),
    'pasteleria_Monoporciones_Fondant Baileys': require('../../assets/product_images/pasteleria/Monoporciones/Fondant_Baileys.png'),
    'pasteleria_Monoporciones_Fondant de chocolate belga': require('../../assets/product_images/pasteleria/Monoporciones/Fondant_de_chocolate_belga.png'),
    'pasteleria_Monoporciones_Crepe de chocolate': require('../../assets/product_images/pasteleria/Monoporciones/Crepe_de_chocolate.png'),
    'pasteleria_Monoporciones_Coulant de Chocolate': require('../../assets/product_images/pasteleria/Monoporciones/Coulant_de_Chocolate.png'),
    'pasteleria_Monoporciones_Brownie con nueces': require('../../assets/product_images/pasteleria/Monoporciones/Brownie_con_nueces.png'),
    'pasteleria_Monoporciones_Torrija Caramelizada de Brioche': require('../../assets/product_images/pasteleria/Monoporciones/Torrija_Caramelizada_de_Brioche.png'),
    'pasteleria_Monoporciones_Tatín Manzana': require('../../assets/product_images/pasteleria/Monoporciones/Tatin_Manzana.png'),
    'pasteleria_Monoporciones_Profiteroles de nata': require('../../assets/product_images/pasteleria/Monoporciones/Profiteroles_de_nata.png'),
    'smoothies_Smoothies_Natural Green': require('../../assets/product_images/smoothies/Smoothies/Natural_Green.png'),
    'smoothies_Smoothies_Mango Fresh': require('../../assets/product_images/smoothies/Smoothies/Mango_Fresh.png'),
    'smoothies_Smoothies_Peach Paradise': require('../../assets/product_images/smoothies/Smoothies/Peach_Paradise.png'),
    'smoothies_Smoothies_Piña Colada': require('../../assets/product_images/smoothies/Smoothies/Pina_Colada.png'),
    'smoothies_Smoothies_Red Banana': require('../../assets/product_images/smoothies/Smoothies/Red_Banana.png'),
    'smoothies_Smoothies_Tropic Mix': require('../../assets/product_images/smoothies/Smoothies/Tropic_Mix.png'),
    'postres de menu_Menú Helado_Vasito premium nata y café': require('../../assets/product_images/postres_de_menu/Menú_Helado/Vasito_premium_nata_y_cafe.png'),
    'postres de menu_Menú Helado_Vasito premium chocolate absoluto': require('../../assets/product_images/postres_de_menu/Menú_Helado/Vasito_premium_chocolate_absoluto.png'),
    'postres de menu_Menú Helado_Vasito premium vainilla con chocolate': require('../../assets/product_images/postres_de_menu/Menú_Helado/Vasito_premium_vainilla_con_chocolate.png'),
    'postres de menu_Menú Helado_Vasito premium nata y fresa': require('../../assets/product_images/postres_de_menu/Menú_Helado/Vasito_premium_nata_y_fresa.png'),
    'postres de menu_Menú Helado_Vasito premium sorbete limón': require('../../assets/product_images/postres_de_menu/Menú_Helado/Vasito_premium_sorbete_limon.png'),
    'postres de menu_Menú Helado_Cono turrón': require('../../assets/product_images/postres_de_menu/Menú_Helado/Cono_turron.png'),
    'postres de menu_Menú Helado_Cono nata': require('../../assets/product_images/postres_de_menu/Menú_Helado/Cono_nata.png'),
    'postres de menu_Menú Helado_Cono limón': require('../../assets/product_images/postres_de_menu/Menú_Helado/Cono_limon.png'),
    'postres de menu_Menú Helado_Bombón Vainilla': require('../../assets/product_images/postres_de_menu/Menú_Helado/Bombon_Vainilla.png'),
    'postres de menu_Menú Helado_Media Bola Leche Merengada': require('../../assets/product_images/postres_de_menu/Menú_Helado/Media_Bola_Leche_Merengada.png'),
    'postres de menu_Menú Helado_Media Bola Vainilla': require('../../assets/product_images/postres_de_menu/Menú_Helado/Media_Bola_Vainilla.png'),
    'postres de menu_Menú Helado_Bloque vainilla': require('../../assets/product_images/postres_de_menu/Menú_Helado/Bloque_vainilla.png'),
    'postres de menu_Menú Helado_Bloque tres gustos': require('../../assets/product_images/postres_de_menu/Menú_Helado/Bloque_tres_gustos.png'),
    'postres de menu_Menú Helado_Bloque nata': require('../../assets/product_images/postres_de_menu/Menú_Helado/Bloque_nata.png'),
    'postres de menu_Menú Helado_Bloque turrón': require('../../assets/product_images/postres_de_menu/Menú_Helado/Bloque_turron.png'),
    'postres de menu_Graneles 6l. menú_Graneles 6L. Restauración Nata': require('../../assets/product_images/postres_de_menu/Graneles_6l._menú/Graneles_6L__Restauracion_Nata.png'),
    'postres de menu_Graneles 6l. menú_Graneles 6L. Restauración Vainilla': require('../../assets/product_images/postres_de_menu/Graneles_6l._menú/Graneles_6L__Restauracion_Vainilla.png'),
    'postres de menu_Graneles 6l. menú_Graneles 6L. Restauración Sorbete limón': require('../../assets/product_images/postres_de_menu/Graneles_6l._menú/Graneles_6L__Restauracion_Sorbete_limon.png'),
    'postres de menu_Graneles 6l. menú_Graneles 6L. Restauración Chocolate': require('../../assets/product_images/postres_de_menu/Graneles_6l._menú/Graneles_6L__Restauracion_Chocolate.png'),
    'postres de menu_Graneles 6l. menú_Graneles 6L. Restauración Fresa': require('../../assets/product_images/postres_de_menu/Graneles_6l._menú/Graneles_6L__Restauracion_Fresa.png'),
    'postres de menu_Lingotes - Pastelería_Tarta Queso con Arándanos': require('../../assets/product_images/postres_de_menu/Lingotes_-_Pastelería/Tarta_Queso_con_Arandanos.png'),
    'postres de menu_Lingotes - Pastelería_Tarta San Marcos': require('../../assets/product_images/postres_de_menu/Lingotes_-_Pastelería/Tarta_San_Marcos.png'),
    'postres de menu_Lingotes - Pastelería_Tarta Selva Trufa': require('../../assets/product_images/postres_de_menu/Lingotes_-_Pastelería/Tarta_Selva_Trufa.png'),
    'postres de menu_Lingotes - Pastelería_Tarta Tiramisú': require('../../assets/product_images/postres_de_menu/Lingotes_-_Pastelería/Tarta_Tiramisu.png'),
    'postres de menu_Lingotes - Pastelería_Brownie con Nueces': require('../../assets/product_images/postres_de_menu/Lingotes_-_Pastelería/Brownie_con_Nueces.png'),
    'bolleria_Productos de Bollería_Pancake Tortitas': require('../../assets/product_images/bolleria/Productos_de_Bollería/Pancake_Tortitas.png'),
    'bolleria_Productos de Bollería_Gofre Belga': require('../../assets/product_images/bolleria/Productos_de_Bollería/Gofre_Belga.png'),
    'bolleria_Productos de Bollería_Crepe artesano': require('../../assets/product_images/bolleria/Productos_de_Bollería/Crepe_artesano.png'),
    'bolleria_Productos de Bollería_Croissant mantequilla': require('../../assets/product_images/bolleria/Productos_de_Bollería/Croissant_mantequilla.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza tartufo e prociutto': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_tartufo_e_prociutto.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Verdure Vegana': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Verdure_Vegana.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Hawaii Tropical': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Hawaii_Tropical.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Carbonara': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Carbonara.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza 5 Formaggi': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_5_Formaggi.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Pollo alla salsa barbecue': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Pollo_alla_salsa_barbecue.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Diavola': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Diavola.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Prociutto e Funghi': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Prociutto_e_Funghi.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Prociutto e Formaggio': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Prociutto_e_Formaggio.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Tonno e Cipolla': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Tonno_e_Cipolla.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Margherita': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Margherita.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Pizza Base de Tomate': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Pizza_Base_de_Tomate.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Caja Pizza Take Away': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Caja_Pizza_Take_Away.png'),
    'cocina de nestle_Pizzas Artesanales Estilo Napolitano_Cuña Cartón Pizza 30x30 CM': require('../../assets/product_images/cocina_de_nestle/Pizzas_Artesanales_Estilo_Napolitano/Cuna_Carton_Pizza_30x30_CM.png'),
    'cocina de nestle_Pizzas y Piccolinis  Buitoni_Pizza cuatro quesos': require('../../assets/product_images/cocina_de_nestle/Pizzas_y_Piccolinis__Buitoni/Pizza_cuatro_quesos.png'),
    'cocina de nestle_Pizzas y Piccolinis  Buitoni_Pizza atún': require('../../assets/product_images/cocina_de_nestle/Pizzas_y_Piccolinis__Buitoni/Pizza_atun.png'),
    'cocina de nestle_Pizzas y Piccolinis  Buitoni_Pizza jamón yorq y queso': require('../../assets/product_images/cocina_de_nestle/Pizzas_y_Piccolinis__Buitoni/Pizza_jamon_yorq_y_queso.png'),
    'cocina de nestle_Pizzas y Piccolinis  Buitoni_Pizza margarita': require('../../assets/product_images/cocina_de_nestle/Pizzas_y_Piccolinis__Buitoni/Pizza_margarita.png'),
    'cocina de nestle_Pizzas y Piccolinis  Buitoni_Caja Pizza Take Away': require('../../assets/product_images/cocina_de_nestle/Pizzas_y_Piccolinis__Buitoni/Caja_Pizza_Take_Away.png'),
    'cocina de nestle_Pizzas y Piccolinis  Buitoni_Cuña Cartón Pizza 30x30 CM': require('../../assets/product_images/cocina_de_nestle/Pizzas_y_Piccolinis__Buitoni/Cuna_Carton_Pizza_30x30_CM.png'),
    'cocina de nestle_Platos y tapas_Fingers de pollo': require('../../assets/product_images/cocina_de_nestle/Platos_y_tapas/Fingers_de_pollo.png'),
    'cocina de nestle_Platos y tapas_Pechugas de pollo': require('../../assets/product_images/cocina_de_nestle/Platos_y_tapas/Pechugas_de_pollo.png'),
    'cocina de nestle_Platos y tapas_Alitas de pollo a la barbacoa': require('../../assets/product_images/cocina_de_nestle/Platos_y_tapas/Alitas_de_pollo_a_la_barbacoa.png'),
    'cocina de nestle_Platos y tapas_Tortilla de patata y cebolla': require('../../assets/product_images/cocina_de_nestle/Platos_y_tapas/Tortilla_de_patata_y_cebolla.png'),
}